- 
  name: Install Percona-release
  apt:
    deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    state: present
- 
  name: add pbm repository to apt
  command: percona-release enable pbm release
  become: yes
  changed_when: False
- 
  name: install pbm
  apt:
    name: percona-backup-mongodb
    update_cache: yes
    state: present
- 
  name: configure PBM_MONGODB_URI for pbm-agent
  ansible.builtin.lineinfile:
    path: /etc/default/pbm-agent
    regexp: '^PBM_MONGODB_URI='
    line: PBM_MONGODB_URI="mongodb://pbmuser:{{ pbmuser_password }}@localhost:{{ mongod_port }}"
    create: yes
- 
  name: configure permanent environment variable
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    regexp: '^export PBM_MONGODB_URI='
    line: export PBM_MONGODB_URI=mongodb://pbmuser:{{ pbmuser_password }}@{{ MONGODB_CONFIG_SERVER_URI }}
- 
  name: configure permanent environment variable - root
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    regexp: '^export PBM_MONGODB_URI='
    line: export PBM_MONGODB_URI=mongodb://pbmuser:{{ pbmuser_password }}@{{ MONGODB_CONFIG_SERVER_URI }}